---
name: KiCAD client packaging
on: # yamllint disable-line rule:truthy
  release:
    branches: master
    types:
      - published
  workflow_dispatch:

jobs:
  create_archive:
    runs-on: windows-2019
    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: Huaqiu-Electronics/kicad-win-builder
          releases-only: true
        id: latest-release

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure
        run: ./build.ps1 -Config -UseMsvcCmake $False

      - name: Checkout any required tools
        run: ./build.ps1 -Init

      - name: Checkout any required tools, setup build environment variables
        run: ./build.ps1 -Env -Arch x64

      - name: Rebuilds vcpkg dependencies
        run: ./build.ps1 -Vcpkg -Latest -Arch x64

      - name: Cache packages downloaded
        uses: actions/cache@v3
        with:
          key: package-downloaded-${{ steps.latest-release.outputs.tag }}
          restore-keys: |
            package-downloaded-
          path: |
            .build
            .downloads
            .support

      - name: Triggers a build
        run: ./build.ps1 -Build -Latest -Arch x64 -BuildType Release

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          key: vcpkg-cache-${{ steps.latest-release.outputs.tag }}
          restore-keys: |
            vcpkg-cache-
          path: |
            vcpkg
            msys64
            msys32

      - name: Triggers a package operation
        run: ./build.ps1 -PreparePackage  -Arch x64   -BuildType Release

      - name: Triggers a package operation Nsis
        run: ./build.ps1 -Package  -PackType Nsis   -Arch x64   -BuildType Release

      - name: Upload installer as asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.HUAQIU_ELECTRONICS_TOKEN }}
          file: ./.out/kicad-huaqiu-${{ steps.latest-release.outputs.tag }}-x86_64.exe
          asset_name: kicad-huaqiu-${{ steps.latest-release.outputs.tag }}-x86_64.exe
          overwrite: true
          tag: ${{ steps.latest-release.outputs.tag }}
